phrase:
  project_id: 30dcea6240582b0c565cf0ed958f779f
  file_format: strings
  pull:
    targets:

    # Core 
    - file: ./Modules/Core/IdentHubSDKCore/Resources/Localization/<locale_code>.lproj/Localizable.strings
      params:
        format_options: { convert_placeholder: true }
        tags: startup,core

    # Qes
    - file: ./Modules/QES/IdentHubSDKQES/Resources/Localization/<locale_code>.lproj/Localizable.strings
      params:
        format_options: { convert_placeholder: true }
        tags: qes

    # Bank
    - file: ./Modules/IdentHubSDKBank/IdentHubSDKBank/Resources/Localization/<locale_code>.lproj/Localizable.strings
      params:
        format_options: { convert_placeholder: true }
        tags: bank

    # Fourthline
    - file: ./Modules/IdentHubSDKFourthline/IdentHubSDKFourthline/Resources/Localization/<locale_code>.lproj/Localizable.strings
      params:
        format_options: { convert_placeholder: true }
        tags: fourthline