name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    env:
      UNIT_TESTS_RESULTS: UnitTestsResults_${{ github.run_number }}#${{ github.run_attempt }}
      SNAPSHOT_TESTS_RESULTS: SnapshotTestsResults_${{ github.run_number }}#${{ github.run_attempt }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pod repo add fourthline-specs https://${{ secrets.FOURTHLINE_COCOAPODS_USER }}:${{ secrets.FOURTHLINE_COCOAPODS_TOKEN }}@github.com/Fourthline-com/FourthlineSDK-iOS-Specs.git
        pod install
    - name: Build For Testing
      run: |
        xcodebuild -workspace IdentHubSDK.xcworkspace -scheme IdentHubSDK -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" build-for-testing

    - name: Run Unit Tests
      id: unit_tests
      run: |
        xcodebuild -workspace IdentHubSDK.xcworkspace -scheme IdentHubSDK -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" -resultBundlePath $UNIT_TESTS_RESULTS.xcresult test-without-building
    - name: Archive Unit Tests Results
      if: ${{ failure() && steps.unit_tests.conclusion == 'failure' }}
      run: |
        zip -r $UNIT_TESTS_RESULTS.zip $UNIT_TESTS_RESULTS.xcresult/
    - name: Upload Unit Tests Results
      if: ${{ failure() && steps.unit_tests.conclusion == 'failure' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.UNIT_TESTS_RESULTS }}
        path: ${{ env.UNIT_TESTS_RESULTS }}.zip
        retention-days: 1
        if-no-files-found: ignore
    - name: Build Sample App
      run: |
        xcodebuild -workspace IdentHubSDK.xcworkspace -scheme Sample -destination "platform=iOS Simulator,name=iPhone 12" build

