name: Sync to upstream repository

on:
  release:
    types: [ released ]

jobs:
  sync:

    if: ${{ github.repository != 'Solarisbank/identhub-ios' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Push to upstream
      env:
        upstream_token: ${{ secrets.UPSTREAM_TOKEN }}
      run: |
        git switch -c main
        git push https://$upstream_token@github.com/Solarisbank/identhub-ios.git main
        git push https://$upstream_token@github.com/Solarisbank/identhub-ios.git --tags
