name: Sync to upstream repository

on:
  release:
    types: [ released ]

jobs:
  sync:

    if: ${{ github.repository != 'Solarisbank/identhub-ios' }}
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      run: |
        git clone https://github.com/$GITHUB_REPOSITORY identhub-ios
    - name: Checkout release version
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/tags/}
        git checkout $RELEASE_VERSION -b $RELEASE_VERSION
      working-directory: identhub-ios
    - name: Push to upstream
      run: |
        git remote set-url origin https://github.com/Solarisbank/identhub-ios.git
        git push origin main
        git push --tags
      working-directory: identhub-ios
