name: Sync to upstream repository

on:
  release:
    types: [ released ]

jobs:
  sync:

    if: ${{ github.repository != 'Solarisbank/identhub-ios' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Push to upstream
      env:
        API_TOKEN_GITHUB: ${{ secrets.UPSTREAM_TOKEN }}
        USER_NAME_GITHUB: ${{ secrets.UPSTREAM_USER }}
      run: |
        git switch -c main
        git push "https://$USER_NAME_GITHUB:$API_TOKEN_GITHUB@github.com/Solarisbank/identhub-ios.git" main
        git push "https://$USER_NAME_GITHUB:$API_TOKEN_GITHUB@github.com/Solarisbank/identhub-ios.git" --tags
